name: creaturesagainstcancer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59344
title: Creatures Against Cancer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2563827699050307
  lightness: 0.9689699176233262
  saturation: 0.943766359705478
  rhythmicContrast: 0.5254506440833211
purpose: []
